exports.TodoNotificationConstants = Object.freeze({
  MISSING_TIMESHEET: "Missing Timesheet",
  TIMESHEET_APPROVAL: "Timesheet Approval",
  LEAVE_APPROVAL: "Leave Approval",
  COMPOFF_APPROVAL: "Comp-Off Approval",
  COMPOFF_MENTEES: "Comp-Off Mentees",
  LEAD_APPRAISAL: "Lead Appraisal",
  REVIEWER_APPRAISAL: "Reviewer Appraisal",
  INITIATE_APPRAISAL: "Initiate Appraisal",
  IN_360_APPRAISAL: "In360 Appraisal",
  IN_CONCLUSION: "In Conclusion",
  SELF_APPRAISAL: "Self Appraisal",
  IR_APPROVAL: "IR Approval",
  APPLY_IR: "Apply IR",
  REJECTED_TIMESHEET: "Rejected Timesheet",
  LWP_TO_BE_SETTLED: "LWP To Be Settled",
  IR_TO_BE_SETTLED: "IR To Be Settled",
  SAT_SUN_WORKING_DAY: "Sat/Sun Working Day",
  MY_TEAM_LEAVES: "My Team Leaves",
  PENDING_LOAN_APPROVALS: "Pending Loan Approvals",
  BIRTHDAY_TEMPLATE_APPROVAL: "Birthday Template Approval",
  MEDICLAIM_APPROVALS: "Mediclaim Approvals",
  PENDING_FULL_SETTLEMENTS: "Pending Full Settlements",
  PAYROLL_MONTH_EMIS: "Payroll Month EMIS",
  UPLOAD_BIRTHDAY_IMAGE: "Upload Birthday Image",
  APPLY_FOR_MEDICLAIM: "Apply For Mediclaim",
  TO_BE_DISBURSED: "Loan To be Disbursed",
  LOW_PETTYCASH_WALLET_AMOUNT: "Wallet Balance",
  OPEN_VOUCHER: "Open Voucher",
  PENDING_VOUCHER_CHANGE_REQUESTS: "Voucher Change Requests",
});
