export const currencyMap = {
  AFN: {
    name: 'Afghan Afghani',
    altName: '',
    countryName: 'Afghanistan',
    symbol: '؋',
    ISO4217: 'AFN',
  },
  ALL: {
    name: 'Lek',
    altName: '',
    countryName: 'Albania',
    symbol: 'L',
    ISO4217: 'ALL',
  },
  DZD: {
    name: 'Algerian Dinar',
    altName: '',
    countryName: 'Algeria',
    symbol: 'د.ج',
    ISO4217: 'DZD',
  },
  EUR: {
    name: 'Andorran Euro',
    altName: '',
    countryName: 'Andorra',
    symbol: '€',
    ISO4217: 'EUR',
  },
  AOA: {
    name: 'Kwanza',
    altName: '',
    countryName: 'Angola',
    symbol: 'Kz',
    ISO4217: 'AOA',
  },
  ARS: {
    name: 'Argentine Peso',
    altName: '',
    countryName: 'Argentina',
    symbol: '$',
    ISO4217: 'ARS',
  },
  AMD: {
    name: 'Armenian Dram',
    altName: '',
    countryName: 'Armenia',
    symbol: '֏',
    ISO4217: 'AMD',
  },
  AUD: {
    name: 'Australian Dollar',
    altName: '',
    countryName: 'Australia',
    symbol: '$',
    ISO4217: 'AUD',
  },
  AZN: {
    name: 'Azerbaijani Manat',
    altName: '',
    countryName: 'Azerbaijan',
    symbol: '₼',
    ISO4217: 'AZN',
  },
  BSD: {
    name: 'Bahamian Dollar',
    altName: '',
    countryName: 'Bahamas',
    symbol: '$',
    ISO4217: 'BSD',
  },
  BHD: {
    name: 'Bahraini Dinar',
    altName: '',
    countryName: 'Bahrain',
    symbol: '.د.ب',
    ISO4217: 'BHD',
  },
  BDT: {
    name: 'Bangladeshi Taka',
    altName: '',
    countryName: 'Bangladesh',
    symbol: '৳',
    ISO4217: 'BDT',
  },
  BBD: {
    name: 'Barbadian Dollar',
    altName: '',
    countryName: 'Barbados',
    symbol: '$',
    ISO4217: 'BBD',
  },
  BYN: {
    name: 'Belarusian Ruble',
    altName: '',
    countryName: 'Belarus',
    symbol: 'Br',
    ISO4217: 'BYN',
  },
  BZD: {
    name: 'Belize Dollar',
    altName: '',
    countryName: 'Belize',
    symbol: '$',
    ISO4217: 'BZD',
  },
  XOF: {
    name: 'West African CFA Franc',
    altName: '',
    countryName: 'Benin',
    symbol: '₣',
    ISO4217: 'XOF',
  },
  BTN: {
    name: 'Bhutanese Ngultrum',
    altName: '',
    countryName: 'Bhutan',
    symbol: 'Nu.',
    ISO4217: 'BTN',
  },
  BOB: {
    name: 'Bolivian Boliviano',
    altName: '',
    countryName: 'Bolivia',
    symbol: 'Bs.',
    ISO4217: 'BOB',
  },
  BAM: {
    name: 'Bosnia and Herzegovina Convertible Mark',
    altName: '',
    countryName: 'Bosnia and Herzegovina',
    symbol: 'KM',
    ISO4217: 'BAM',
  },
  BWP: {
    name: 'Botswana Pula',
    altName: '',
    countryName: 'Botswana',
    symbol: 'P',
    ISO4217: 'BWP',
  },
  BRL: {
    name: 'Brazilian Real',
    altName: '',
    countryName: 'Brazil',
    symbol: 'R$',
    ISO4217: 'BRL',
  },
  BND: {
    name: 'Brunei Dollar',
    altName: '',
    countryName: 'Brunei',
    symbol: '$',
    ISO4217: 'BND',
  },
  BGN: {
    name: 'Bulgarian Lev',
    altName: '',
    countryName: 'Bulgaria',
    symbol: 'лв',
    ISO4217: 'BGN',
  },
  BIF: {
    name: 'Burundian Franc',
    altName: '',
    countryName: 'Burundi',
    symbol: 'Fr',
    ISO4217: 'BIF',
  },
  CVE: {
    name: 'Cabo Verdean Escudo',
    altName: '',
    countryName: 'Cabo Verde',
    symbol: 'Esc',
    ISO4217: 'CVE',
  },
  KHR: {
    name: 'Cambodian Riel',
    altName: '',
    countryName: 'Cambodia',
    symbol: '៛',
    ISO4217: 'KHR',
  },
  XAF: {
    name: 'Cameroonian CFA Franc',
    altName: '',
    countryName: 'Cameroon',
    symbol: '₣',
    ISO4217: 'XAF',
  },
  CAD: {
    name: 'Canadian Dollar',
    altName: '',
    countryName: 'Canada',
    symbol: '$',
    ISO4217: 'CAD',
  },
  CLP: {
    name: 'Chilean Peso',
    altName: '',
    countryName: 'Chile',
    symbol: '$',
    ISO4217: 'CLP',
  },
  CNY: {
    name: 'Chinese Yuan',
    altName: '',
    countryName: 'China',
    symbol: '¥',
    ISO4217: 'CNY',
  },
  COP: {
    name: 'Colombian Peso',
    altName: '',
    countryName: 'Colombia',
    symbol: '$',
    ISO4217: 'COP',
  },
  KMF: {
    name: 'Comorian Franc',
    altName: '',
    countryName: 'Comoros',
    symbol: 'Fr',
    ISO4217: 'KMF',
  },
  CDF: {
    name: 'Congolese Franc',
    altName: '',
    countryName: 'Congo (Democratic Republic)',
    symbol: 'Fr',
    ISO4217: 'CDF',
  },
  CRC: {
    name: 'Costa Rican Colón',
    altName: '',
    countryName: 'Costa Rica',
    symbol: '₡',
    ISO4217: 'CRC',
  },
  HRK: {
    name: 'Croatian Kuna',
    altName: '',
    countryName: 'Croatia',
    symbol: 'kn',
    ISO4217: 'HRK',
  },
  CUP: {
    name: 'Cuban Peso',
    altName: '',
    countryName: 'Cuba',
    symbol: '$',
    ISO4217: 'CUP',
  },
  CZK: {
    name: 'Czech Koruna',
    altName: '',
    countryName: 'Czech Republic',
    symbol: 'Kč',
    ISO4217: 'CZK',
  },
  DKK: {
    name: 'Danish Krone',
    altName: '',
    countryName: 'Denmark',
    symbol: 'kr',
    ISO4217: 'DKK',
  },
  DJF: {
    name: 'Djiboutian Franc',
    altName: '',
    countryName: 'Djibouti',
    symbol: 'Fr',
    ISO4217: 'DJF',
  },
  XCD: {
    name: 'East Caribbean Dollar',
    altName: '',
    countryName: 'Dominica',
    symbol: '$',
    ISO4217: 'XCD',
  },
  DOP: {
    name: 'Dominican Peso',
    altName: '',
    countryName: 'Dominican Republic',
    symbol: '$',
    ISO4217: 'DOP',
  },
  USD: {
    name: 'Ecuadorian Dollar',
    altName: '',
    countryName: 'Ecuador',
    symbol: '$',
    ISO4217: 'USD',
  },
  EGP: {
    name: 'Egyptian Pound',
    altName: '',
    countryName: 'Egypt',
    symbol: 'ج.م.',
    ISO4217: 'EGP',
  },
  ERN: {
    name: 'Eritrean Nakfa',
    altName: '',
    countryName: 'Eritrea',
    symbol: 'Nkf',
    ISO4217: 'ERN',
  },
  SZL: {
    name: 'Eswatini Lilangeni',
    altName: '',
    countryName: 'Eswatini',
    symbol: 'E',
    ISO4217: 'SZL',
  },
  ETB: {
    name: 'Ethiopian Birr',
    altName: '',
    countryName: 'Ethiopia',
    symbol: 'ብር',
    ISO4217: 'ETB',
  },
  INR: {
    name: 'Indian Rupee',
    altName: '',
    countryName: 'India',
    symbol: '₹',
    ISO4217: 'INR',
  },
};
