export const languageMap = {
  fas: {
    name: 'Persian (Farsi)',
    altName: 'فارسی (Fārsi)',
    ISO6391: 'fa',
    ISO6392: 'fas',
    ISO6393: 'fas',
  },
  vie: {
    name: 'Vietnamese',
    altName: 'Tiếng Việt',
    ISO6391: 'vi',
    ISO6392: 'vie',
    ISO6393: 'vie',
  },
  tam: {
    name: 'Tamil',
    altName: 'தமிழ் (Tamiḻ)',
    ISO6391: 'ta',
    ISO6392: 'tam',
    ISO6393: 'tam',
  },
  tur: {
    name: 'Turkish',
    altName: 'Türkçe',
    ISO6391: 'tr',
    ISO6392: 'tur',
    ISO6393: 'tur',
  },
  ita: {
    name: 'Italian',
    altName: 'Italiano',
    ISO6391: 'it',
    ISO6392: 'ita',
    ISO6393: 'ita',
  },
  pa: {
    name: 'Punjabi',
    altName: 'ਪੰਜਾਬੀ (Pañjābī)',
    ISO6391: 'pa',
    ISO6392: 'pan',
    ISO6393: 'pan',
  },
  jav: {
    name: 'Javanese',
    altName: 'ꦧꦱꦗꦮ (Basa Jawa)',
    ISO6391: '',
    ISO6392: 'jav',
    ISO6393: 'jav',
  },
  deu: {
    name: 'German',
    altName: 'Deutsch',
    ISO6391: 'de',
    ISO6392: 'deu',
    ISO6393: 'deu',
  },
  swa: {
    name: 'Swahili',
    altName: 'Kiswahili',
    ISO6391: 'sw',
    ISO6392: 'swa',
    ISO6393: 'swa',
  },
  jpn: {
    name: 'Japanese',
    altName: '日本語 (Nihongo)',
    ISO6391: 'ja',
    ISO6392: 'jpn',
    ISO6393: 'jpn',
  },
  por: {
    name: 'Portuguese',
    altName: 'Português',
    ISO6391: 'pt',
    ISO6392: 'por',
    ISO6393: 'por',
  },
  rus: {
    name: 'Russian',
    altName: 'Русский (Russkiy)',
    ISO6391: 'ru',
    ISO6392: 'rus',
    ISO6393: 'rus',
  },
  bn: {
    name: 'Bengali',
    altName: 'বাংলা (Bānlā)',
    ISO6391: 'bn',
    ISO6392: 'ben',
    ISO6393: 'ben',
  },
  fra: {
    name: 'French',
    altName: 'Français',
    ISO6391: 'fr',
    ISO6392: 'fra',
    ISO6393: 'fra',
  },
  ar: {
    name: 'Arabic',
    altName: 'العربية (Al-‘Arabīyah)',
    ISO6391: 'ar',
    ISO6392: 'ara',
    ISO6393: 'ara',
  },
  hi: {
    name: 'Hindi',
    altName: 'हिन्दी',
    ISO6391: 'hi',
    ISO6392: 'hin',
    ISO6393: 'hin',
  },
  zh: {
    name: 'Mandarin Chinese',
    altName: '中文 (Zhōngwén)',
    ISO6391: 'zh',
    ISO6392: 'zho',
    ISO6393: 'zho',
  },
  es: {
    name: 'Spanish',
    altName: 'Español',
    ISO6391: 'es',
    ISO6392: 'spa',
    ISO6393: 'spa',
  },
  en: {
    name: 'English',
    altName: 'Englisch',
    ISO6391: 'en',
    ISO6392: 'eng',
    ISO6393: 'eng',
  },
  ko: {
    name: 'Korean',
    altName: '한국어 (Hangug-eo)',
    ISO6391: 'ko',
    ISO6392: 'kor',
    ISO6393: 'kor',
  },
  ta: {
    name: 'Tamil',
    altName: 'தமிழ் (Tamiḻ)',
    ISO6391: 'ta',
    ISO6392: 'tam',
    ISO6393: 'tam',
  },
};
