export const AuditLogsExamples = {
  create: {
    ok: {
      body: {
        tenantId: '6788a32231f106f00f06f909',
        userId: '6788a32231f106f00f06f911',
        entity: 'users',
        action: 'PATCH',
        documentId: '678a301484a599ddb8394ec1',
        modifiedData: {
          _id: '678a301484a599ddb8394ec1',
          name: 'thisisupdated',
          nameLocale: 'namejkj',
          email: 'john.doe123erereer@example.com',
          password: 'tv&V40QO*y',
          roleId: '6788a32231f106f00f06f90e',
          isActive: true,
          isDeleted: false,
          createdAt: '2025-01-17T10:25:24.278Z',
          updatedAt: '2025-01-21T07:42:26.901Z',
          __v: 0,
        },
        message: 'Operation sucessful.',
        statusCode: 200,
        ipAddress: '::1',
      },
      expected: {
        output: {
          tenantId: '6788a32231f106f00f06f909',
          userId: '6788a32231f106f00f06f911',
          entity: 'users',
          action: 'PATCH',
          documentId: '678a301484a599ddb8394ec1',
          modifiedData: {
            _id: '678a301484a599ddb8394ec1',
            name: 'thisisupdated',
            nameLocale: 'namejkj',
            email: 'john.doe123erereer@example.com',
            password: 'tv&V40QO*y',
            roleId: '6788a32231f106f00f06f90e',
            isActive: true,
            isDeleted: false,
            createdAt: '2025-01-17T10:25:24.278Z',
            updatedAt: '2025-01-21T07:42:26.901Z',
            __v: 0,
          },
          message: 'Operation sucessful.',
          statusCode: 200,
          ipAddress: '::1',
          _id: '678f4fe3d29ef217babf536e',
          createdAt: '2025-01-21T07:42:27.010Z',
          updatedAt: '2025-01-21T07:42:27.010Z',
          __v: 0,
        },
      },
    },
    badRequest: {
      body: {
        action: 'create',
      },
    },
  },
  list: {
    ok: {
      expected: {
        output: [
          {
            _id: '67972c009affa79f20b0391b',
            entity: 'Tenant',
            action: 'CREATE',
            modifiedData: {
              '0': {
                companyName: 'app',
                domainUrl: 'app.genesisapps.in',
                primaryLanguage: 'en',
                countryDetails: {
                  name: 'India',
                  altName: 'Bharat',
                  ISO31661A2: 'IN',
                  ISO31661A3: 'IND',
                },
                secondaryLanguageDetails: {
                  name: 'Hindi',
                  altName: 'हिन्दी',
                  ISO6391: 'hi',
                  ISO6392: 'hin',
                  ISO6393: 'hin',
                },
                currencyDetails: {
                  name: 'Indian Rupee',
                  altName: '',
                  countryName: 'India',
                  symbol: '₹',
                  ISO4217: 'INR',
                },
                isActive: true,
                isDeleted: false,
                _id: '67972c009affa79f20b03919',
                createdAt: '2025-01-27T06:47:28.053Z',
                updatedAt: '2025-01-27T06:47:28.053Z',
                __v: 0,
              },
            },
            statusCode: 201,
            ipAddress: '::1',
            createdAt: '2025-01-27T06:47:28.097Z',
            updatedAt: '2025-01-27T06:47:28.097Z',
            __v: 0,
          },
          {
            _id: '67972c009affa79f20b03922',
            entity: 'Role',
            action: 'CREATE',
            modifiedData: {
              '0': {
                name: 'Master Admin',
                tenantId: '67972c009affa79f20b03919',
                scopes: [
                  {
                    entity: 'tenants',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'roles',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'api_keys',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'users',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'categories',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'suggestions',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'items',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'feedbacks',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'activity_logs',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'auth',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'audit_logs',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                ],
                isActive: true,
                isDeleted: false,
                _id: '67972c009affa79f20b0391c',
                __v: 0,
                createdAt: '2025-01-27T06:47:28.092Z',
                updatedAt: '2025-01-27T06:47:28.092Z',
              },
              '1': {
                name: 'Super Admin',
                tenantId: '67972c009affa79f20b03919',
                scopes: [
                  {
                    entity: 'tenants',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'roles',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'api_keys',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'users',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'categories',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'suggestions',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'items',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'feedbacks',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'activity_logs',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'auth',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                  {
                    entity: 'audit_logs',
                    read: { self: true, all: true },
                    write: { self: true, all: true },
                  },
                ],
                isActive: true,
                isDeleted: false,
                _id: '67972c009affa79f20b0391d',
                __v: 0,
                createdAt: '2025-01-27T06:47:28.092Z',
                updatedAt: '2025-01-27T06:47:28.092Z',
              },
            },
          },
        ],
      },
    },
  },
};
